CollegeMap/Models/CollegeMapModels/College.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CollegeMap.Models.CollegeMapModels
{
    public class College
    {
        // maximum number of entries to use google api to compute driving distance
        public const int MAX_DRIVE_DIST_ENTRIES = 15;

        public string Name { get; set; }
        public string Description { get; set; }
        public int ID { get; set; }

        // CollegeScorecard.com ID
        [Display(Name = "CollegeScorecard.com ID")]
        public int CollegeScorecardID { get; set; }

        // Non-Degree, Certificat, Associate, Bachelors, Graduate
        [Display(Name = "Highest Degree")]
        public DegreeType HighestDegreeOffered { get; set; }
        // Total enrollment
        [DisplayFormat(DataFormatString = "{0:n0}")]
        public int Enrollment { get; set; }
        // public private, for-profit
        public CollegeType Type { get; set; }

        [Display(Name = "Tuition - In State")]
        [DisplayFormat(DataFormatString = "{0:c0}")]
        public int AnnualTuition { get; set; }

        [Display(Name = "Tuition - Out of State")]
        [DisplayFormat(DataFormatString = "{0:c0}")]
        public int AnnualTuitionOut { get; set; }

        [Display(Name = "Acceptance Rate")]
        [DisplayFormat(DataFormatString = "{0:P1}")]
        public float AcceptanceRate { get; set; }

        // The average annual total cost of attendance, including tuition and fees, 
        // books and supplies, and living expenses, minus the average grant/scholarship aid. 
        [Display(Name = "Average Annual Net Cost of Attendance")]
        [DisplayFormat(DataFormatString = "{0:c0}")]
        public int AvgNetPrice { get; set; }

        public string State { get; set; }
        public string Website { get; set; }
        // Address can be anything google maps can handle
        public string Address { get; set; }
        // distance used at query time, based on home location used in the query
        public int Distance { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        [Display(Name = "Graduation Rate")]
        [DisplayFormat(DataFormatString = "{0:P1}")]
        public float GraduationRate { get; set; }

        [Display(Name = "Percentage of White Students")]
        [DisplayFormat(DataFormatString = "{0:P1}")]
        public float PercentWhite { get; set; }

    }
}

CollegeMap/Models/CollegeMapModels/CollegeType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CollegeMap.Models.CollegeMapModels
{
    public class CollegeType
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public IList<College> Colleges { get; set; }
    }
}

CollegeMap/Controllers/CollegesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CollegeMap.Data;
using CollegeMap.Models.CollegeMapModels;
using CollegeMap.Models.CollegeMapViewModels;
using System.Net;
using System.Text.RegularExpressions;
using System.IO;
using Newtonsoft.Json;
using CsvHelper;
using X.PagedList;
using System.Reflection;

namespace CollegeMap.Controllers
{
    public class CollegesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public struct Location
        {
            public float Lat;
            public float Lon;
        }

        public static async Task<Location> GetLocationFromAddress(string address)
        {
            string addressNoWhitespace = Regex.Replace(address, "\\s+", "+");

            HttpWebRequest request =
                (HttpWebRequest)WebRequest.Create("https://maps.googleapis.com/maps/api/geocode/json?address="
                + addressNoWhitespace
                + "&key=AIzaSyDZlFiNuQsfssb97q19gLwKWvpdb4ptC-U");

            float lat = 0.0F;
            float lon = 0.0F;

            WebResponse response = await request.GetResponseAsync();
            using (var streamReader = new StreamReader(response.GetResponseStream()))
            {
                var result = streamReader.ReadToEnd();

                if (!string.IsNullOrEmpty(result))
                {
                    JSON_Position.Rootobject rootData = JsonConvert.DeserializeObject<JSON_Position.Rootobject>(result);
                    // loop in reverse since deletion of entries affects indices
                    if (rootData.status == "OK")
                    {
                        lat = rootData.results[0].geometry.location.lat;
                        lon = rootData.results[0].geometry.location.lng;
                    }
                }

            }
            Location location = new Location
            {
                Lat = lat,
                Lon = lon
            };
            return location;

        }

        public CollegesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Colleges
        public async Task<IActionResult> Index(int? page, string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            int pageNumber = page ?? 1; // if no page was specified in the querystring, default to the first page (1)
            IEnumerable<College> colleges = await _context.Colleges.
                Include(c => c.Type).Include(c => c.HighestDegreeOffered).
                OrderBy(c => c.Name).
                ToListAsync();
            if (!String.IsNullOrEmpty(searchString))
            {
                colleges = colleges.Where(c => c.Name.ToUpper().Contains(searchString.ToUpper()));
            }
            var onePageOfColleges = colleges.ToPagedList(pageNumber, 25);
            return View(onePageOfColleges);
        }

        // GET: Colleges/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var college = await _context.Colleges.Include(c => c.Type).Include(c => c.HighestDegreeOffered)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (college == null)
            {
                return NotFound();
            }

            return View(college);
        }

        // GET: Colleges/Create
        public IActionResult Create()
        {
            IEnumerable<CollegeType> collegeTypes = _context.CollegeTypes.ToList();
            IEnumerable<DegreeType> degreeTypes = _context.DegreeTypes.ToList();
            AddCollegeViewModel addCollegeViewModel = new AddCollegeViewModel(collegeTypes, degreeTypes);
            return View(addCollegeViewModel);
        }

        // POST: Colleges/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddCollegeViewModel addCollegeViewModel)
        {
            if (ModelState.IsValid)
            {
                CollegeType newCollegeType =
                    _context.CollegeTypes.Single(c => c.ID == addCollegeViewModel.CollegeTypeID);
                DegreeType newDegreeType =
                    _context.DegreeTypes.Single(c => c.ID == addCollegeViewModel.DegreeTypeID);

                Location location = await GetLocationFromAddress(addCollegeViewModel.Address);

                College college = new College
                {
                    Name = addCollegeViewModel.Name,
                    Description = addCollegeViewModel.Description,
                    CollegeScorecardID = addCollegeViewModel.CollegeScorecardID,
                    Enrollment = addCollegeViewModel.Enrollment,
                    AnnualTuition = addCollegeViewModel.AnnualTuition,
                    AnnualTuitionOut = addCollegeViewModel.AnnualTuitionOut,
                    AcceptanceRate = addCollegeViewModel.AcceptanceRate,
                    AvgNetPrice = addCollegeViewModel.AvgNetPrice,
                    Website = addCollegeViewModel.Website,
                    Address = addCollegeViewModel.Address,
                    Latitude = location.Lat,
                    Longitude = location.Lon,
                    State = addCollegeViewModel.State,
                    Type = newCollegeType,
                    HighestDegreeOffered = newDegreeType
                };
                _context.Add(college);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(addCollegeViewModel);
        }

        // GET: Colleges/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var college = await _context.Colleges.Include(c => c.Type).Include(c => c.HighestDegreeOffered).SingleOrDefaultAsync(m => m.ID == id);
            if (college == null)
            {
                return NotFound();
            }
            IEnumerable<CollegeType> collegeTypes = _context.CollegeTypes.ToList();
            IEnumerable<DegreeType> degreeTypes = _context.DegreeTypes.ToList();
            AddCollegeViewModel addCollegeViewModel = new AddCollegeViewModel(collegeTypes, degreeTypes);
            addCollegeViewModel.ID = (int)id;
            addCollegeViewModel.CollegeScorecardID = college.CollegeScorecardID;
            addCollegeViewModel.Address = college.Address;
            addCollegeViewModel.State = college.State;
            addCollegeViewModel.AnnualTuition = college.AnnualTuition;
            addCollegeViewModel.AnnualTuitionOut = college.AnnualTuitionOut;
            addCollegeViewModel.AcceptanceRate = college.AcceptanceRate;
            addCollegeViewModel.AvgNetPrice = college.AvgNetPrice;
            addCollegeViewModel.CollegeTypeID = college.Type.ID;
            addCollegeViewModel.DegreeTypeID = college.HighestDegreeOffered.ID;
            addCollegeViewModel.Description = college.Description;
            addCollegeViewModel.Enrollment = college.Enrollment;
            addCollegeViewModel.Name = college.Name;
            addCollegeViewModel.Website = college.Website;
            return View(addCollegeViewModel);

        }

        // POST: Colleges/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AddCollegeViewModel addCollegeViewModel)
        {

                        if (ModelState.IsValid)
                        {
                            try
                            {
                                College college = await _context.Colleges.Include(c => c.Type).Include(c => c.HighestDegreeOffered).SingleOrDefaultAsync(m => m.ID == addCollegeViewModel.ID);
                                if (college == null)
                                {
                                    return NotFound();
                                }
                                CollegeType newCollegeType =
                                    _context.CollegeTypes.Single(c => c.ID == addCollegeViewModel.CollegeTypeID);
                                DegreeType newDegreeType =
                                    _context.DegreeTypes.Single(c => c.ID == addCollegeViewModel.DegreeTypeID);
                                college.State = addCollegeViewModel.State;
                                college.Address = addCollegeViewModel.Address;

                                Location location = await GetLocationFromAddress(addCollegeViewModel.Address);
                                college.Latitude = location.Lat;
                                college.Longitude = location.Lon;

                                college.CollegeScorecardID = addCollegeViewModel.CollegeScorecardID;

                                college.AnnualTuition = addCollegeViewModel.AnnualTuition;
                                college.AnnualTuitionOut = addCollegeViewModel.AnnualTuitionOut;
                                college.AcceptanceRate = addCollegeViewModel.AcceptanceRate;
                                college.AvgNetPrice = addCollegeViewModel.AvgNetPrice;
                                college.Type = newCollegeType;
                                college.HighestDegreeOffered = newDegreeType;

CollegeMap/Controllers/DegreeTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CollegeMap.Data;
using CollegeMap.Models.CollegeMapModels;

namespace CollegeMap.Controllers
{
    public class DegreeTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DegreeTypesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: DegreeTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.DegreeTypes.ToListAsync());
        }

        // GET: DegreeTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var degreeType = await _context.DegreeTypes
                .SingleOrDefaultAsync(m => m.ID == id);
            if (degreeType == null)
            {
                return NotFound();
            }

            return View(degreeType);
        }

        // GET: DegreeTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DegreeTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] DegreeType degreeType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(degreeType);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(degreeType);
        }

        // GET: DegreeTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var degreeType = await _context.DegreeTypes.SingleOrDefaultAsync(m => m.ID == id);
            if (degreeType == null)
            {
                return NotFound();
            }
            return View(degreeType);
        }

        // POST: DegreeTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] DegreeType degreeType)
        {
            if (id != degreeType.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(degreeType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DegreeTypeExists(degreeType.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(degreeType);
        }

        // GET: DegreeTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var degreeType = await _context.DegreeTypes
                .SingleOrDefaultAsync(m => m.ID == id);
            if (degreeType == null)
            {
                return NotFound();
            }

            return View(degreeType);
        }

        // POST: DegreeTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var degreeType = await _context.DegreeTypes.SingleOrDefaultAsync(m => m.ID == id);
            _context.DegreeTypes.Remove(degreeType);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool DegreeTypeExists(int id)
        {
            return _context.DegreeTypes.Any(e => e.ID == id);
        }
    }
}

CollegeMap/Views/Colleges/Create.cshtml
@model CollegeMap.Models.CollegeMapViewModels.AddCollegeViewModel

@{
    ViewData["Title"] = "Create College";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>College</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CollegeTypeID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="CollegeTypeID" asp-items="Model.CollegeTypes"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DegreeTypeID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="DegreeTypeID" asp-items="Model.DegreeTypes"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Enrollment" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Enrollment" class="form-control" />
                <span asp-validation-for="Enrollment" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AcceptanceRate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AcceptanceRate" class="form-control" />
                <span asp-validation-for="AcceptanceRate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AnnualTuition" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AnnualTuition" class="form-control" />
                <span asp-validation-for="AnnualTuition" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AnnualTuitionOut" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AnnualTuitionOut" class="form-control" />
                <span asp-validation-for="AnnualTuitionOut" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AvgNetPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AvgNetPrice" class="form-control" />
                <span asp-validation-for="AvgNetPrice" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Website" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="State" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CollegeMap/Views/Colleges/Delete.cshtml
@model CollegeMap.Models.CollegeMapModels.College

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>College</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.Enrollment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Enrollment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AnnualTuition)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AnnualTuition)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

CollegeMap/Views/Colleges/Details.cshtml
@model CollegeMap.Models.CollegeMapModels.College

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>College</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Highest Degree Offered
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HighestDegreeOffered.Name)
        </dd>
        <dt>
            College Type
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Enrollment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Enrollment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PercentWhite)
        </dt>
        <dd>
            @if (Model.PercentWhite == 0)
            {
                <text>N/A</text>

            }
            else
            {
                @Html.DisplayFor(model => model.PercentWhite)
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AcceptanceRate)
        </dt>
        <dd>
            @if (Model.AcceptanceRate == 0)
            {
                <text>N/A</text>

            }
            else
            {
                @Html.DisplayFor(model => model.AcceptanceRate)
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GraduationRate)
        </dt>
        <dd>
            @if (Model.GraduationRate == 0)
            {
                <text>N/A</text>

            }
            else
            {
                @Html.DisplayFor(model => model.GraduationRate)
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AnnualTuition)
        </dt>
        <dd>
            @if (Model.AnnualTuition == 0)
            {
                <text>N/A</text>

            }
            else
            {
                @Html.DisplayFor(model => model.AnnualTuition)
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AnnualTuitionOut)
        </dt>
        <dd>
            @if (Model.AnnualTuitionOut == 0)
            {
                <text>N/A</text>

            }
            else
            {
                @Html.DisplayFor(model => model.AnnualTuitionOut)
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AvgNetPrice)
        </dt>
        <dd>
            @if (Model.AvgNetPrice == 0)
            {
                <text>N/A</text>

            }
            else
            {
                @Html.DisplayFor(model => model.AvgNetPrice)
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd>
            <a href="@Html.DisplayFor(model => model.Website)">@Html.DisplayFor(model => model.Website)</a>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>
    </dl>
</div>

CollegeMap/Views/Colleges/Edit.cshtml
@model CollegeMap.Models.CollegeMapViewModels.AddCollegeViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>College</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CollegeTypeID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="CollegeTypeID" asp-items="Model.CollegeTypes"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DegreeTypeID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="DegreeTypeID" asp-items="Model.DegreeTypes"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Enrollment" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Enrollment" class="form-control" />
                <span asp-validation-for="Enrollment" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AcceptanceRate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AcceptanceRate" class="form-control" />
                <span asp-validation-for="AcceptanceRate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AnnualTuition" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AnnualTuition" class="form-control" />
                <span asp-validation-for="AnnualTuition" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AnnualTuitionOut" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AnnualTuitionOut" class="form-control" />
                <span asp-validation-for="AnnualTuitionOut" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AvgNetPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AvgNetPrice" class="form-control" />
                <span asp-validation-for="AvgNetPrice" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Website" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="State" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CollegeMap/Views/Colleges/Import.cshtml
@{
    ViewData["Title"] = "Import";
}

<h2>Import</h2>

<p>
    @ViewData["ImportMessage"]
</p>

<p>
    <a asp-controller="Colleges" asp-action="Maintenance">Return to College Maintenance</a>
</p>

CollegeMap/Views/Colleges/Maintenance.cshtml
@{
    ViewData["Title"] = "Maintenance";
}

<h2>Maintenance</h2>
<p>
    <a asp-controller="Colleges" asp-action="Index">Maintain Colleges</a>
</p>
<p>
    <a asp-controller="DegreeTypes" asp-action="Index">Maintain Degree Types</a>
</p>
<p>
    <a asp-controller="CollegeTypes" asp-action="Index">Maintain College Types</a>
</p>
<form asp-controller="Colleges"  asp-action="Import" method="get">
    <div class="form-actions no-color">
        <p>
            College Data Provider: <input type="text" name="Source" />
            Data Version: <input type="text" name="Version" />
            <input type="submit" value="Import" class="btn btn-default" />
        </p>
    </div>
</form>